 
services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile  
    ports:
      - "443:443" 
    networks:
      - app-network
    volumes:
      - ./logs/modsec.log:/var/log/modsec_audit.log  # เชื่อมต่อไฟล์ modsec.log กับ modsec_audit.log ใน container

networks:
  app-network:
    external: true