 
services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile  
 
    ports:
      - "80:80"
    networks:
      - app-network  

networks:
  app-network: 
    driver: bridge  
